name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Testing
      run: ./gradlew assembleDebug lint testDebugUnitTest -p library
    - name: Upload asset to release
      uses: actions-github/upload-to-release@master
      env:
        GITHUB_TOKEN: 4e17389c39f5a05a1a1b8b470df45535159f760a
      with:
        file: 'library/build/report'
        type: 'application/octet-stream'
