# .github/workflows/android.yml

name: Android CI

# on: [push]
on:
  pull_request:
    branches: 
     - '*' 
     - '!master' 
     - '!release*'
  push:
    branches:
      - 'master' 
#      - '*' 
#      - '!master' 
#      - '!release*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build App with Gradle
      run: ./gradlew assembleDebug
    - name: Testing
      run: ./gradlew assembleDebug lint testDebugUnitTest -p library
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Testing
      uses: actions/upload-artifact@v1
      with:
        name: library-test
        path: library/build/reports/tests/testDebugUnitTest
    - name: Upload library artifact
      uses: actions/upload-artifact@v1
      with:
        name: library-aar
        path: library/build/outputs/aar/library-debug.aar
    - name: Jacoco
      run: ./gradlew jacocoTestReport
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=boosttag
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=contactBoostTag_MyApplication
           -Dsonar.sources=app/../library/src/main/java
           -Dsonar.tests=library/src/test/java
           -Dsonar.junit.reportsPath=library/build/test-results/debug
           -Dsonar.jacoco.reportPath=library/build/jacoco/testDebugUnitTest.exec
           
#     - name: show
#       run: cat /opt/hostedtoolcache/sonar-scanner/4.2.0.1873/x64/sonar-scanner-4.2.0.1873-linux/conf/sonar-scanner.properties
