name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Testing
      run: ./gradlew assembleDebug lint testDebugUnitTest -p library
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: Test Result
        # Destination path
        path: library/build/report
